[project]
name = "portfolio-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "pytest>=9.0.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.50",
    "typer>=0.26.7",
]
[tool.pytest.ini_options]
pythonpath = [
  "src",
]
